#pragma once

#define print1 if(breakpoints!=2){printf("  ┏━━━━━┓\n⇨ ┃ p=2 ┃\n  ┗━━━━━┛\n     ↓\n  ┏━━━━━━━━━━━━┓\n  ┃ teilt p n? ┃←━━━━━━━┓\n  ┗━━━━━━━━━━━━┛        ┃\n     Nein    Ja         ┃\n       ↓     ↓          ┃\n  ┏━━━━━━┓  ┏━━━━━━━━━┓ ┃\n  ┃ p++  ┃  ┃ p -> PT ┃ ┃\n  ┃ p≤√n ┃  ┃ n /= p  ┃ ┃\n  ┗━━━━━━┛  ┗━━━━━━━━━┛ ┃\n  Nein Ja         ↓     ┃\n    ↓   ┗━━━━━━━━━━━━━━━┛\n  ┏━━━━━━━━┓\n  ┃ output ┃\n  ┗━━━━━━━━┛\n\n n = %lli \n p = %lli\nPress any Key to continue....\n\n",n,p);if (breakpoints == 1)getchar();}

#define print2 if(breakpoints!=2){printf("  ┏━━━━━┓\n  ┃ p=2 ┃\n  ┗━━━━━┛\n     ↓\n  ┏━━━━━━━━━━━━┓\n⇨ ┃ teilt p n? ┃←━━━━━━━┓\n  ┗━━━━━━━━━━━━┛        ┃\n     Nein    Ja         ┃\n       ↓     ↓          ┃\n  ┏━━━━━━┓  ┏━━━━━━━━━┓ ┃\n  ┃ p++  ┃  ┃ p -> PT ┃ ┃\n  ┃ p≤√n ┃  ┃ n /= p  ┃ ┃\n  ┗━━━━━━┛  ┗━━━━━━━━━┛ ┃\n  Nein Ja         ↓     ┃\n    ↓   ┗━━━━━━━━━━━━━━━┛\n  ┏━━━━━━━━┓\n  ┃ output ┃\n  ┗━━━━━━━━┛\n\n n = %lli \n p = %lli\nPress any Key to continue....\n\n",n,p);if (breakpoints == 1)getchar();}

#define print3 if(breakpoints!=2){printf("  ┏━━━━━┓\n  ┃ p=2 ┃\n  ┗━━━━━┛\n     ↓\n  ┏━━━━━━━━━━━━┓\n  ┃ teilt p n? ┃←━━━━━━━┓\n  ┗━━━━━━━━━━━━┛        ┃\n     Nein    Ja         ┃\n       ↓     ↓          ┃\n  ┏━━━━━━┓  ┏━━━━━━━━━┓ ┃\n  ┃ p++  ┃⇨ ┃ p -> PT ┃ ┃\n  ┃ p≤√n ┃  ┃ n /= p  ┃ ┃\n  ┗━━━━━━┛  ┗━━━━━━━━━┛ ┃\n  Nein Ja         ↓     ┃\n    ↓   ┗━━━━━━━━━━━━━━━┛\n  ┏━━━━━━━━┓\n  ┃ output ┃\n  ┗━━━━━━━━┛\n\n n = %lli \n p = %lli\nPress any Key to continue....\n\n",n,p);if (breakpoints == 1)getchar();}

#define print4 if(breakpoints!=2){printf("  ┏━━━━━┓\n  ┃ p=2 ┃\n  ┗━━━━━┛\n     ↓\n  ┏━━━━━━━━━━━━┓\n  ┃ teilt p n? ┃←━━━━━━━┓\n  ┗━━━━━━━━━━━━┛        ┃\n     Nein    Ja         ┃\n       ↓     ↓          ┃\n  ┏━━━━━━┓  ┏━━━━━━━━━┓ ┃\n⇨ ┃ p++  ┃  ┃ p -> PT ┃ ┃\n  ┃ p≤√n ┃  ┃ n /= p  ┃ ┃\n  ┗━━━━━━┛  ┗━━━━━━━━━┛ ┃\n  Nein Ja         ↓     ┃\n    ↓   ┗━━━━━━━━━━━━━━━┛\n  ┏━━━━━━━━┓\n  ┃ output ┃\n  ┗━━━━━━━━┛\n\n n = %lli \n p = %lli\nPress any Key to continue....\n\n",n,p);if (breakpoints == 1)getchar();}

#define print5 if(breakpoints!=2){printf("  ┏━━━━━┓\n  ┃ p=2 ┃\n  ┗━━━━━┛\n     ↓\n  ┏━━━━━━━━━━━━┓\n  ┃ teilt p n? ┃←━━━━━━━┓\n  ┗━━━━━━━━━━━━┛        ┃\n     Nein    Ja         ┃\n       ↓     ↓          ┃\n  ┏━━━━━━┓  ┏━━━━━━━━━┓ ┃\n  ┃ p++  ┃  ┃ p -> PT ┃ ┃\n  ┃ p≤√n ┃  ┃ n /= p  ┃ ┃\n  ┗━━━━━━┛  ┗━━━━━━━━━┛ ┃\n  Nein Ja         ↓     ┃\n    ↓   ┗━━━━━━━━━━━━━━━┛\n  ┏━━━━━━━━┓\n⇨ ┃ output ┃\n  ┗━━━━━━━━┛\n\n n = %lli \n p = %lli\nPress any Key to continue....\n\n",n,p);if (breakpoints == 1)getchar();}

